### ISSUE TITLE
关于评论区加载缓慢（Waline）以及一些小问题

### ISSUE THREAD

**Issue by Meyerclex** [Ice-Hazymoon/hugo-theme-luna#1]
您好~ 这个主题真是太漂亮啦！而且功能非常完善，在我发现它的第一时间就打算更替博客主题了！但在我配置途中遇到了一些问题：

1. Waline评论区加载缓慢
我使用的是Waline的评论区，按照文档的提示我在`comment.html`引入了[Waline文档提供的Html内容](https://waline.js.org/guide/get-started.html#html-%E5%BC%95%E5%85%A5-%E5%AE%A2%E6%88%B7%E7%AB%AF)：
这是我[仓库内的文件](https://github.com/Meyerclex/luna/blob/872e39a8fea50894c8555670f3f0cb3d991305df/layouts/partials/comment.html)。实装以后我发现它加载很慢（可以说是完全不加载）我读了您的文档说“然后在……添加脚本的初始化部分”，我想这是我的配置问题。不太能理解，不知道您是否能提供一些帮助呢？😥我的blog：https://gregueria.icu/about/ 评论区需要在页面里刷新一下才能出现，并且无法展开已有评论。

![加载很慢](https://raw.githubusercontent.com/Meyerclex/image/main/20220506011520.png)

2. 在我更替了icon.png后网站图标仍然无法正确显示。
我替换的是[这一份文件](https://github.com/Meyerclex/luna/blob/872e39a8fea50894c8555670f3f0cb3d991305df/assets/icon.png)。并且在hugo server中它可以正常显示。

![](https://raw.githubusercontent.com/Meyerclex/image/main/20220506012710.png)

3. 一些feature的问题
因为已经有了字数显示啦，所以我想取消显示阅读时间，在config.toml中写了几次都没有办法取消，请问我该如何更改呢？
或许会考虑加一个“全站字数”的feature吗？
（这部分不太紧要，我可以慢慢摸索修改一下的XD）

5. 或许会考虑增添侧边悬浮的目录吗？:D

6. Front-matter
Hugo的Frontmatter里的description在这个主题中似乎不起作用，为文章写过的description在这里似乎显示为每篇文章的前几十个字。 
并且似乎frontmatter中设置`draft: true` 的文章会自动显示出来。

7. 似乎这个主题在hugo server的加载中有些沉重和迟缓，偶尔本地修改的东西需要很久才能在本地预览中看见。

**Comment by Ice-Hazymoon** [comment]
你可以像下面这样添加你的评论系统

[comment.html](https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/main/layouts/partials/comment.html)

```html
<div class="border-t py-6 px-6 md:px-8 dark:border-darkBorder">
    <div id="waline"></div>

    <script data-swup-reload-script>
        setTimeout(() => {
            console.log(document.getElementById('waline'))
            window.waline = Waline.init({
                el: '#waline',
                serverURL: 'https://again-eight.vercel.app/',
                emoji: ['https://cdn.jsdelivr.net/gh/norevi/blob-emoji-for-waline@2.0/blobs-gif', 'https://cdn.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs', 'https://cdn.jsdelivr.net/gh/norevi/blob-emoji-for-waline@2.0/blobs-png'],
                requiredMeta: ['name', 'email', 'url'],
            });
        }, 1000);
    </script>
</div>
```

[custom/head.html](https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/main/layouts/partials/custom/head.html)

```html
<script src="https://unpkg.com/@waline/client@v2/dist/waline.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@waline/client@v2/dist/waline.css"/>
```

**Comment by Meyerclex** [comment]
太感谢您了！！我的评论区和About页面已经修好了！！Icon也正常显示啦！
😭😭呜哇真是太开心啦，我马上拿着新主题的博客出去传教！期待新的Toc！
关于description是这样的：我之前所有的文章front-matter里都是用‘description’作为文章摘要/描述，后来发现Luna主题里这个变量是‘Summary’。没找到一次性替换的方法…后面再说吧XD 非常感谢您的帮助和这个美丽的主题！

**Comment by Ice-Hazymoon** [comment]
> 太感谢您了！！我的评论区和About页面已经修好了！！Icon也正常显示啦！
> 😭😭呜哇真是太开心啦，我马上拿着新主题的博客出去传教！期待新的Toc！
> 关于description是这样的：我之前所有的文章front-matter里都是用‘description’作为文章摘要/描述，后来发现Luna主题里这个变量是‘Summary’。没找到一次性替换的方法…后面再说吧XD 非常感谢您的帮助和这个美丽的主题！

`Summary` 这个是hugo官方自带的描述变量，其他主题应该是修改过所以不太一样，直接用vscode之类的编辑器全局替换一遍吧
