### ISSUE TITLE
报错相关问题

### ISSUE THREAD

**Issue by lemonchor** [Ice-Hazymoon/hugo-theme-luna#13]
Ice-Hazymoon您好！很喜欢您的luna主题，但是我在使用过程中遇到了问题 ：(

1、不知道到底有没有安装对，瞎鼓捣了之后试着本地预览，它生成本地预览的时间很长，还出现了一大串报错，但是最后也能成功生成预览，然后我试着改了站点名字和图标居然成功了，不过之后再次生成预览时图标又变回默认的了orz。我想请教您这些报错问题我应该怎样解决，是不是我安装错误了

![w1](https://user-images.githubusercontent.com/104574934/174331386-1b641327-50de-4be1-877a-07cc73e83c2d.png)

2、还有试了一下部署到vercel，出现了以下报错，我看不懂是哪里的问题，也没在网络上找到解决办法，所以冒昧请教

![w3](https://user-images.githubusercontent.com/104574934/174329731-fed6f7eb-c0b3-44dd-8d2e-0e0db0799924.png)

希望得到您的帮助，谢谢您！

**Comment by Ice-Hazymoon** [comment]
如果用到了加密功能，需要在加密的地方设置一个密码，或者在配置文件中设置一个默认密码

如果用到了 twitter 模板，需要终端可以访问 twitter，在中国大陆通常不可用，需要手动设置代理

对于 vercel 的支持我还没有适配过，对这方面不太了解，不过我近期会对 netlify 和 vercel 的支持

第一次生成慢是因为在处理图片，如果不希望使用图片处理功能可以在配置文件中关闭

**Comment by lemonchor** [comment]
hi！谢谢您的回复~

重新安装了很多次之后现在已经不报错了，本地运行时所有功能都可以使用，速度也变快了！

不过我又遇到了大问题orz，就是在本地预览一切都正常，但是没法托管到站点，只能自己在本地欣赏（呜呜

但是这个应该不是主题的问题，我再努力看看能不能解决

以及想请问一下应该在哪里修改网站的图标，试了很多都没成功

最后谢谢您美丽的主题~ 谢谢您的帮助~

**Comment by Ice-Hazymoon** [comment]
可用图标在 https://akveo.github.io/eva-icons/ 这里查询
然后在 https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/master/layouts/partials/custom/icons.html 这里把类名添加进去就可以在全站使用了

**Comment by lemonchor** [comment]
不好意思没有表达清楚，我想问的是那个绿色的icon怎么改来着

**Comment by Ice-Hazymoon** [comment]
https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/master/static/icon.png

**Comment by lemonchor** [comment]
谢谢您!已经成功了~
