### ISSUE TITLE
主题使用求助

### ISSUE THREAD

**Issue by gclm** [Ice-Hazymoon/hugo-theme-luna#15]
1. 如何自定义 footer 添加备案号等信息
2. 如何配置评论不在友情链接和关于我页面展示啊

**Comment by Ice-Hazymoon** [comment]
更新一下主题，然后：

在 [footer.html](https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/master/layouts/partials/custom/footer.html) 添加自定义的 footer 信息

如果不希望评论在某个页面显示，设置 `comments: false` 就行

**Comment by gclm** [comment]
关于备案号能不能修改移动到这个位置呢》
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/27618687/175194077-dc281b29-f3b0-4ad6-a32e-0299bfff287c.png">

**Comment by gclm** [comment]
另外这个图片如何配置成每个文章封面都不一样呢？现在每个图片都一样
<img width="933" alt="image" src="https://user-images.githubusercontent.com/27618687/175270501-6a990b4a-a350-4f5c-a7d5-00c0fac3dfe6.png">

**Comment by Ice-Hazymoon** [comment]
> 另外这个图片如何配置成每个文章封面都不一样呢？现在每个图片都一样
> <img width="933" alt="image" src="https://user-images.githubusercontent.com/27618687/175270501-6a990b4a-a350-4f5c-a7d5-00c0fac3dfe6.png">
> 

如果你的图片是远程的随机图片地址，可能会出现图片都一样的情况，这是图片服务器缓存问题，与本主题无关

> 关于备案号能不能修改移动到这个位置呢》
> <img width="1154" alt="image" src="https://user-images.githubusercontent.com/27618687/175194077-dc281b29-f3b0-4ad6-a32e-0299bfff287c.png">
> 

不可以，如有需要可以自己修改主题文件，该主题不会对备案号这类小众内容进行适配

**Comment by Ice-Hazymoon** [comment]
现在增加了 `{{timestamp}}` 变量，你可以设置为 `https://unsplash.it/1920/1080/?random={{timestamp}}` 来显示随机图片，更新一下主题即可
