### ISSUE TITLE
baseURL config not effective

### ISSUE THREAD

**Issue by vitahlin** [Ice-Hazymoon/hugo-theme-luna#20]
- hugo v0.101.0+extended darwin/arm64 BuildDate=unknown
- node v16.15.0

The config.yaml
```
baseURL: https://www.vitahlin.com/
languageCode: zh-cn
defaultContentLanguage: zh-cn
title: "VitahLin"
enableRobotsTXT: true
enableEmoji: true
theme: hugo-theme-luna
timeout: 60000
timeZone: Asia/Shanghai
```

Then I run `hugo` the cname content in public directory always is `hugo-theme-luna.imiku.me`

**Comment by Ice-Hazymoon** [comment]
这不可能啊，你尝试修改其他变量看看是否有变化，或者在开发模式下看看是否能正常运行

**Comment by vitahlin** [comment]
其他变量正常的
