### ISSUE TITLE
How to disable TOC on assets/README.md

### ISSUE THREAD

**Issue by dfranco** [Ice-Hazymoon/hugo-theme-luna#22]
Hello,

I'm testing your Hugo theme and was wondering how I can disable toc on assets/README.md ?

Linked to this question, can we set page for home instead of posts list ?

Details:
hugo version: 0.101.0-ext
theme version: latest

Thanks for your feedback

**Comment by Ice-Hazymoon** [comment]
You can delete the file assets/README.md, or disable it [here](https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/e10f8bd9be8a948707eea95e6555a2e62fd3bc1d/exampleSite/config.yaml#L180)

About the settings of the home page. I have not tried it, I am not sure if it is a feature of hugo, I will test it soon, You can try it yourself or wait a few more days

Have a nice day!

**Comment by dfranco** [comment]
Thanks @Ice-Hazymoon 

I'll have a try on my side too.

In the meantime, I manage to disable toc in config.

Quick question, if toc is set to false, is there a way to remove numbers before each h2, h3, h4 etc. ?

**Comment by Ice-Hazymoon** [comment]
https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/master/exampleSite/config.yaml#L232-L232

set it to false
