### ISSUE TITLE
Error: Error building site: POSTCSS: failed to transform "main.css" (text/css): 'ss' �����ڲ����ⲿ���Ҳ���ǿ����еĳ��� ���������ļ���

### ISSUE THREAD

**Issue by atongmu-love** [Ice-Hazymoon/hugo-theme-luna#28]
我运行报这个错误，不知道怎么解决，我直接将exampleSite下的config文件直接替换了站点根目录的config文件，hugo版本是hugo v0.104.0-c744dbd6edeeb27288c9dd67e0eb92951f911397+extended，nodejs版本是v16.17.1
![image](https://user-images.githubusercontent.com/78579037/194796631-4537d9c0-960a-45e8-8e77-353a33fea472.png)

**Comment by Ice-Hazymoon** [comment]
按理说应该是 main.scss 而不是 main.css，有没有修改过其它地方

**Comment by Ice-Hazymoon** [comment]
更新一下postcss试试

**Comment by atongmu-love** [comment]
> 按理说修改应该是main.scss而不是main.css，有没有过其他地方

就按照教程做了这几步
git submodule add -b master https://github.com/Ice-Hazymoon/hugo-theme-luna themes/hugo-theme-luna
cd themes/hugo-theme-luna
npm install --production
最后在根目录下执行了hugo server -D，就这一步报那个错误
其他的也没改什么

**Comment by atongmu-love** [comment]
> 更新一下postcss试试

我将hugo和nodejs的版本换成了0.104.0和16.0.0成功了，之前用的都是最新版。感谢指导
