### ISSUE TITLE
关于导航栏Icon更改的问题

### ISSUE THREAD

**Issue by Meyerclex** [Ice-Hazymoon/hugo-theme-luna#3]
打扰了！我看到文档中写“图标可以在 [Eva icons](https://akveo.github.io/eva-icons) 查询”。
于是在config.yaml中直接更改了icon：
![image](https://user-images.githubusercontent.com/94032239/169683873-53cd908f-4e49-434e-b74f-4fd8ba6f8c42.png) 

尽管我在本地预览中能够看到图标正常显示，也用command“hugo”生成了Public文件再Push，但网站中始终有一些图标（比如Home-outline。以及我测试了Eva icons里的其他图标比如headphones-outline也不行）没有办法正常显示出来：
![image](https://user-images.githubusercontent.com/94032239/169683953-448eb0be-0731-4013-8d32-2627ece5aba9.png)

或许是我更改图标的方式有误吗？请问我应该如何更改呢？希望能得到解答（以及感谢新版本的浮动TOC和Shortcodes^^！非常好用！很喜欢这个主题！）

**Comment by Ice-Hazymoon** [comment]
试试 `hugo --gc -v --minify --cleanDestinationDir`

**Comment by Meyerclex** [comment]
> 试试 `hugo --gc -v --minify --cleanDestinationDir`

![image](https://user-images.githubusercontent.com/94032239/169684535-337a83ac-ac06-4384-9109-2fb9a204a204.png)
😥还是不太行…我更改的是：
![image](https://user-images.githubusercontent.com/94032239/169684610-26cabc61-53f3-4db0-a388-22b2bd177dae.png)

还有另外一个疑问是，当页面类型是About页面一样的Page时，似乎画廊排版（`![](1.jpg) ![](2.jpg) ![](3.jpg)`）是没有办法正常显示的？
我尝试将[这个页面](https://gregueria.icu/posts/album/)更改为page（Front-matter里写`type: page` `layout: "page"`）。但是所有图片都以正常大小排布，只有在Posts里好像才能正常用画廊排版的shortcodes。

**Comment by Ice-Hazymoon** [comment]
图标问题修复了，在 [icons.html](https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/d0a5e8ec74d274be146443c145e61fde09701011/layouts/partials/custom/icons.html) 中添加相应的图标类即可，默认情况下会清除所有未使用的图标来减少css大小

至于另外一个问题我抽时间再修修

**Comment by Meyerclex** [comment]
可以显示了，感谢！^^
