### ISSUE TITLE
Problems with one page hosting on github

### ISSUE THREAD

**Issue by DJE98** [Ice-Hazymoon/hugo-theme-luna#31]
I tried to host the theme as one page public side on my repository
[sketching-with-hardware-project](https://github.com/DJE98/sketching-with-hardware-project). For that I modified the [gh-pages.yml](https://github.com/DJE98/sketching-with-hardware-project/blob/e7a1eb0f2b9d92b1ba7e34d9d5011bea80164fd8/.github/workflows/gh-pages.yml). In the [readme](https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/08886ca9342a2a31cb06a8dac715ff2735b00891/README.md) is not explicitly defined what I have to change for deploying my [website](https://dje98.github.io/sketching-with-hardware-project/). Could describe what I am doing wrong?

**Comment by Ice-Hazymoon** [comment]
https://github.com/DJE98/sketching-with-hardware-project/blob/e7a1eb0f2b9d92b1ba7e34d9d5011bea80164fd8/.github/workflows/gh-pages.yml#L7

please delete this line
