### ISSUE TITLE
How to modify the style of highlighted code blocks?

### ISSUE THREAD

**Issue by waidinsamkeit** [Ice-Hazymoon/hugo-theme-luna#34]
How to modify the style of highlighted code blocks? I don't like the default color scheme

**Comment by Ice-Hazymoon** [comment]
see https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/08886ca9342a2a31cb06a8dac715ff2735b00891/exampleSite/config.yaml#L177

https://gohugo.io/getting-started/configuration-markup#highlight
