### ISSUE TITLE
Error building site: POSTCSS: failed to transform "main.css" (text/css):

### ISSUE THREAD

**Issue by kokoro7755** [Ice-Hazymoon/hugo-theme-luna#46]
您好！
想使用luna主题，但是建站过程中报了这个错误：
Error building site: POSTCSS: failed to transform "main.css" (text/css): Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'

已经安装了最新版的 hugo-extended，NodeJs，postcss-cli。
不知道是不是哪里没配好……搜了一下也没有得到解决（大多是让安装最新的扩展版本）。
用其他主题试了一下，很快就搭好了，不知道为什么这次遇到了这个错误orz
希望得到您的解答！

**Comment by Ice-Hazymoon** [comment]
cd themes/hugo-theme-luna
npm install --production

这个运行了吗

**Comment by kokoro7755** [comment]
> cd themes/hugo-theme-luna npm install --production
> 
> 这个运行了吗

运行了=（
