### ISSUE TITLE
想问下普通文章可以调整图片大小吗？

### ISSUE THREAD

**Issue by Leticiooo** [Ice-Hazymoon/hugo-theme-luna#60]
文章中插入图片默认铺满整个宽度很不好看，所以我尝试了
```
<div  align="center">    
  <img src="1.jpg" width="50%" height="50%">
</div>
```
测试发现在gallery模式下可以实现图片缩小并居中，但默认的文章格式就不能，请问应该在哪里修改呀？谢谢！

**Comment by Ice-Hazymoon** [comment]
https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/e1a4109a9fb53ecb20ce8b59d12a00d9c79453ad/assets/sass/typo.scss#L281

`@apply my-4 rounded dark:border-darkBorder w-auto mx-auto max-w-[50%];`
