### ISSUE TITLE
启动报错了，无法访问GitHub API

### ISSUE THREAD

**Issue by x-haose** [Ice-Hazymoon/hugo-theme-luna#61]
Start building sites …
hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended windows/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
ERROR 2023/01/08 21:59:41 Failed to get JSON resource "https://api.github.com/repos/Ice-Hazymoon/hugo-theme-luna": Failed to retrieve remote file: Not Found, body: "{\"error\":\"Not Found\"}"
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
ERROR 2023/01/08 21:59:41 Failed to get JSON resource "https://api.github.com/users/Ice-Hazymoon/repos?per_page=100&type=owner": Failed to retrieve remote file: Not Found, body: "{\"error\":\"Not Found\"}"
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Error: Error building site: failed to render pages: render of "page" failed: "E:\hugo-blog\themes\hugo-theme-luna\layouts\_default\github.html:21:26": execute of template failed: template: _default/github.html:21:26: executing "main" at <sort $githubData "stargazers_count" "desc">: error calling sort: sequence must be provided
Built in 5920 ms

**Comment by Ice-Hazymoon** [comment]
删除github和Twitter页面
