### ISSUE TITLE
固定顶栏时，页内链接跳转锚点被顶栏遮挡

### ISSUE THREAD

**Issue by Cystee** [Ice-Hazymoon/hugo-theme-luna#67]
![image](https://user-images.githubusercontent.com/61391190/215337894-67e635c7-8741-451d-b86f-105d054ecf9a.png)
比如点目录，跳转的位置似乎是从页面顶部计算的而不是导航栏底部

**Comment by Ice-Hazymoon** [comment]
已修复 https://github.com/Ice-Hazymoon/hugo-theme-luna/commit/d7cc9c27ea997d92c4b32a41f8d53da4eeeb28c5
