### ISSUE TITLE
站点域名修改无效

### ISSUE THREAD

**Issue by guowei-gong** [Ice-Hazymoon/hugo-theme-luna#75]
嗨。我修改了项目根目录下 config.toml
![image](https://user-images.githubusercontent.com/62499904/219631584-757ec280-38e6-4a71-8b8f-ef7fb2600b3f.png)

但是编译出的 CNAME 始终为 hugo-theme-luna.imiku.me
![image](https://user-images.githubusercontent.com/62499904/219631860-bd6943af-816d-4c6c-8fda-7d15f3fcc4ec.png)

我通过 VSCode 全局搜索 hugo-theme-luna.imiku.me，得到的搜索结果看起来没有任何异常。
![image](https://user-images.githubusercontent.com/62499904/219632410-6a1f7dc2-1fbb-414f-8afd-f56be07ad155.png)

**Comment by Ice-Hazymoon** [comment]
修改你网站根目录的配置文件，不要修改主题目录下的

**Comment by guowei-gong** [comment]
> 修改你网站根目录的配置文件，不要修改主题目录下的

感谢你的回复。我已经修改了根目录配置文件中 baseURL 字段，并恢复了之前修改主题目录下的 baseURL 字段。执行 hugo --minify  ，查看 public 下生成的 CNAME，仍然是 hugo-theme-luna.imiku.me

**Comment by guowei-gong** [comment]
我 fork 了本主题，使用 fork 的主题后，我移除了一切 hugo-theme-luna.imiku.me 关键字，我在项目中无法找到任何这个关键字，但是生成出来的 CNAME 仍然是 hugo-theme-luna.imiku.me

**Comment by Ice-Hazymoon** [comment]
把主题目录下的cname文件删了，自己新建一个static/cname文件试试

**Comment by guowei-gong** [comment]
> 把主题目录下的cname文件删了，自己新建一个static/cname文件试试

这对我有用，删除后重新创建，并修改内容为自己的域名。
