### ISSUE TITLE
执行 Github Action Cl 运行错误，如图

### ISSUE THREAD

**Issue by dingminghui** [Ice-Hazymoon/hugo-theme-luna#78]
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/49083552/221505600-5eaf04fa-ee99-4b2e-bcec-16ed08e81760.png">

在未执行到 Deploy 这一步之前，代码未改动

**Comment by Ice-Hazymoon** [comment]
配置文件用的是 https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/master/exampleSite/.github/workflows/main.yml 吗

**Comment by dingminghui** [comment]
@Ice-Hazymoon 已解决
但是部署后样式出现了问题，如图 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/49083552/221516310-1fa0453a-5d6f-4edd-8556-409f4e7748b4.png">

好像是你的 svg 源文件的问题

<img width="995" alt="image" src="https://user-images.githubusercontent.com/49083552/221517538-7869553d-872d-4fc2-9d28-8a9c8b378397.png">

**Comment by Ice-Hazymoon** [comment]
更新一下版本，最新版本没有这个问题

**Comment by dingminghui** [comment]
@Ice-Hazymoon  全部搞定，多谢
