### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by Villode** [Ice-Hazymoon/hugo-theme-luna#79]
WARN 2023/03/05 12:18:24 error calling resources.GetRemote: Get "https://pbs.twimg.com/media/FqSlB1OXwAADR15?format=jpg&name=orig": dial tcp 128.121.243.76:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by Ice-Hazymoon** [comment]
中国大陆用户删除 twitter.md 即可

**Comment by Villode** [comment]
好的，谢谢，解决了。
