### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by m0rml1n** [Ice-Hazymoon/hugo-theme-luna#86]
你好，月月
我最近用了luna主题遇到两个问题。

1. 开启了pjax，使用的是twikoo评论，添加data-swup-reload-script属性，它不能在首次切换到文章页面显示，只能加载过一次后，再进入文章，才能显示评论。
2. 夜间模式没有渲染-GitHub Actions 自动部署

希望在这里可以获得帮助

**Comment by Ice-Hazymoon** [comment]
能提供你部署后的地址吗

**Comment by m0rml1n** [comment]
> 能提供你部署后的地址吗

m0rml1n.github.io

**Comment by Ice-Hazymoon** [comment]
你把评论代码的内容发出来看看

**Comment by Ice-Hazymoon** [comment]
试试下面的

```html
<script src="https://cdn.staticfile.org/twikoo/1.6.15/twikoo.all.min.js" data-swup-reload-script>
```

**Comment by Ice-Hazymoon** [comment]
试试下面的

```html
<script src="https://cdn.staticfile.org/twikoo/1.6.15/twikoo.all.min.js" data-swup-reload-script>
```

**Comment by Ice-Hazymoon** [comment]
关于夜间模式，主题和hugo的版本都是最新的吗，是否有修改过任何地方

**Comment by m0rml1n** [comment]
> 试试下面的
> 
> ```
> <script src="https://cdn.staticfile.org/twikoo/1.6.15/twikoo.all.min.js" data-swup-reload-script>
> ```

換成这样后，评论不显示了
> <div id="tcomment"></div>
>   <script src="https://cdn.staticfile.org/twikoo/1.6.15/twikoo.all.min.js" data-swup-reload-script>
> twikoo.init({
>   envId: 'https://twikoo.nai.si/', 
>   // 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
>   // https://twikoo-m0rml1n.vercel.app/
>   // https://m0rml1n.zeabur.app/
>   // https://twikoo.nai.si/
>   el: '#tcomment', // 容器元素
>   // region: 'ap-guangzhou', // 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
>   // path: location.pathname, // 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数
>   // lang: 'zh-CN', // 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js
> })
> </script>

**Comment by Ice-Hazymoon** [comment]
没写对

```html
<script src="https://cdn.staticfile.org/twikoo/1.6.15/twikoo.all.min.js" data-swup-reload-script ></script>

<script data-swup-reload-script>
      twikoo.init({
          envId: "https://twikoo.nai.si/",
          el: "#tcomment"
      })
</script>
```

**Comment by m0rml1n** [comment]
https://github.com/m0rml1n/hugo-theme-luna/blob/master/themes/hugo-theme-luna/layouts/partials/comments/provider/custom.html
m0rml1n.github.io
清除了缓存看了下，好像还是这样

**Comment by Ice-Hazymoon** [comment]
![image](https://user-images.githubusercontent.com/25239977/231679170-b69148e0-9861-4fca-af74-c5b390b05f93.png)

**Comment by m0rml1n** [comment]
> vercel没生效..

github可以就行了，估计vercel缓存没生效啥的，到时候我在看看啥原因，

> 关于夜间模式，主题和hugo的版本都是最新的吗，是否有修改过任何地方

关于主题和hugo版本，我是 直接 fork  https://github.com/guowei-gong/luna 他的仓库，添加个TOKEN搞的-，-我也不知道有没有改过啥

**Comment by Ice-Hazymoon** [comment]
我也不知道出了什么问题，或许你可以试试本地安装一下hugo和主题看看有没有一样的问题，我闲下来的时候会研究这个bug

**Comment by m0rml1n** [comment]
😄感谢^_^热情的月月

**Comment by Ice-Hazymoon** [comment]
async="false" 删了试试

**Comment by m0rml1n** [comment]
额...我都准备把这个问题删了，放弃改回giscus了
async="false"  在哪个目录文件里啊

**Comment by Ice-Hazymoon** [comment]
我。。我也不知道这是个啥bug，还没仔细研究，先用 giscus 吧，比 twikoo 好看多了

**Comment by minhducnguyen189** [comment]
Hi @Ice-Hazymoon , @m0rml1n , about the dark/light mode. I found the root cause and fixed it on my local machine. It works well for me. You can try by go to postcss.config.js and add the keyword "/:/" into the standard of the safelist as in the image below, then it will work.

![image](https://user-images.githubusercontent.com/45281955/231992581-5eda5d01-382f-4b8a-98bd-91953ef10c30.png)

**Comment by Ice-Hazymoon** [comment]
> Hi @Ice-Hazymoon , @m0rml1n , about the dark/light mode. I found the root cause and fixed it on my local machine. It works well for me. You can try by go to postcss.config.js and add the keyword "/:/" into the standard of the safelist as in the image below, then it will work.
> 
> ![image](https://user-images.githubusercontent.com/45281955/231992581-5eda5d01-382f-4b8a-98bd-91953ef10c30.png)

Thanks! Would replacing /:/ with /dark/ solve the problem?

**Comment by minhducnguyen189** [comment]
> > Hi @Ice-Hazymoon , @m0rml1n , about the dark/light mode. I found the root cause and fixed it on my local machine. It works well for me. You can try by go to postcss.config.js and add the keyword "/:/" into the standard of the safelist as in the image below, then it will work.
> > ![image](https://user-images.githubusercontent.com/45281955/231992581-5eda5d01-382f-4b8a-98bd-91953ef10c30.png)
> 
> Thanks! Would replacing `/:/` with `/dark/` solve the problem?

ah I tried and it's not working by replacing with `/dark/` I think the postcss see the `:` is not in the safelist so it will not append these codes and that why I saw after the css file is generated there is no the css part for changing dark and light mode.

**Comment by Ice-Hazymoon** [comment]
Ok, can you create a PR to modify this file?

**Comment by minhducnguyen189** [comment]
Hi I had created the PR: https://github.com/Ice-Hazymoon/hugo-theme-luna/pull/87. please help me to review. Thanks
